
on: 
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      new_tag_version: ${{ steps.notes.outputs.release_notes }}
    steps:
    - name: Print notes
      run: |
            {
              echo 'JSON_RESPONSE<<EOF'
              curl -L -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/techslaves/spring-boot-docker/releases/latest | jq -r '.body'| sed 's/##//' | sed 's/#//' 
              echo EOF
            } >> "$GITHUB_ENV"
            echo $JSON_RESPONSE
    - name: Get Release notes
      id: notes
      run: |   
        notes=$(curl -L -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/techslaves/spring-boot-docker/releases/latest | jq -r '.body'| sed 's/##//' | sed 's/#//') 
        echo "##################"
        echo $notes

        curl --request POST \
        --url 'https://utsav-garg.atlassian.net/rest/api/3/issue' \
        --user 'er.utsavgarg@gmail.com:ATATT3xFfGF0lWpbQsLm7AxsfhlhN004j1g_btN1J_4t2CqqccZ7nC6N3-H-sjjg_gBdP4Wxut47TR4MW7GkCjhvgrMh2DA0gF0uL2k0PbCA87XQPLbijISXIOiug3pgLhOGvgd6KB30euZS-qK2nf0D43fZ9tuoohpqZCLx-5IaG-dFJwDgv2U=983B797E' \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/json' \
        --data '{
          "fields": {
             "project":
             {
                "id": "10000"
             },
             "customfield_10035": "v1.1.1",
             "summary": "No REST for the Wicked.",
             "description": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "$notes"
                      }
                    ]
                  }
                ]
              },
             "issuetype": {
                "id": "10001"
             }
         }
      }'
    
    - name: Jira Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Jira Create issue
      uses: atlassian/gajira-create@v3
      with:
        project: CR
        issuetype: Task
        summary: ${{ steps.notes.outputs.release_notes }}
        description: "Description"
        fields: '{"customfield_10035": "v1.1.2"}'
