on: 
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      jira_description: ${{ steps.jira_description.outputs.jira_description }}
    steps:
    - name: JIRA DESCRIPTION
      id: jira_description
      run: |
      
         export JIRA_DESCRIPTION=$(curl -L -H "Accept: application/vnd.github+json" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/techslaves/spring-boot-docker/releases/latest | jq -r '.html_url')
         echo "jira_description=${JIRA_DESCRIPTION}" >> "$GITHUB_OUTPUT"
         echo $JIRA_DESCRIPTION
      
    
    - name: Jira Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Jira Create issue
      uses: atlassian/gajira-create@v3
      with:
        project: CR
        issuetype: Task
        summary: "Test"
        description: ${{ steps.jira_description.outputs.JIRA_DESCRIPTION }}
        fields: '{"customfield_10035": "v1.1.1"}'
