
on: 
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      new_tag_version: ${{ steps.notes.outputs.release_notes }}
    steps:
    - name: Print notes
      run: |
            {
              echo 'JSON_RESPONSE<<EOF'
              (curl -L -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/techslaves/spring-boot-docker/releases/latest | jq -r '.body'| sed 's/##//' | sed 's/#//') 
              echo EOF
            } >> "$GITHUB_ENV"
            echo $JSON_RESPONSE
    - name: Get Release notes
      id: notes
      run: |   
        notes=$(curl -L -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/techslaves/spring-boot-docker/releases/latest | jq -r '.body'| sed 's/##//' | sed 's/#//') 
        echo "release_notes=${notes}" >> "$GITHUB_OUTPUT"
        echo $release_notes
        echo "##################"
        echo $notes
    
    - name: Jira Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Jira Create issue
      uses: atlassian/gajira-create@v3
      with:
        project: CR
        issuetype: Task
        summary: ${{ steps.notes.outputs.release_notes }}
        description: "Description"
        fields: '{"customfield_10035": "v1.1.2"}'
