name: trigger-from-jira
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Docker Image tag'
        required: true  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Trigerred from JIRA
      run: |
         echo "Image Tags: ${{ inputs.tags }}"
